spring.application.name=JoseDaniel

server.port=80

logging.parttern.dateformat=hh:mm 
#Netbeans dice que spring boot no reconoce este comando, pero no hay razon del porque, ley un poco en la web y dice que puede ser que Netbeans esta mostrando una alerta falsa

spring.main.banner-mode=off

spring.thymeleaf.cache=false

